export const questions = [
    "lied about my age.",
    "broken a bone.",
    "gotten a speeding ticket.",
    "dyed my hair an unnatural color.",
    "been on a blind date.",
    "eaten something I regretted later.",
    "fallen asleep in public.",
    "sung karaoke.",
    "been on a plane.",
    "lied on a resume.",
    "regretted a major life decision.",
    "pretended to be sick to get out of something.",
    "publicly embarrassed myself.",
    "forgotten someone's name right after they introduced themselves.",
    "talked in sleep.",  
    "eaten something I found on the ground.",
    "broken a promise.",
    "felt completely unprepared for something important.",
    "traveled solo.",
    "been starstruck.",
    "faked a laugh.",
    "cried during a movie.",
    "pulled an all-nighter.",
    "lied to my parents.",
    "gotten a tattoo.",
    "broken someone's heart.",
    "had a secret crush on a teacher.",
    "missed a flight or important event.",
    "cheated on a test.",
    "lied about my hobbies.",
    "gotten food poisoning.",
    "eaten food that was past its expiration date.",
    "sleepwalked.",
    "gotten lost in a city.",
    "lied about how much I can drink.",
    "gotten into a physical fight.",
    "regretted a text message.",
    "lied about my relationship status.",
    "sung along to a song I didn't know the words to.",
    "lied about how many books I've read.",
    "faked an illness to get out of work.",
    "lied about my musical taste.",
    "lied about my age online.",
    "eaten something I'm allergic to.",
    "lied about my travel experiences.",
    "lied about my knowledge of a movie or TV show.",
    "lied about how much money I make.",
    "lied about my workout routine." ]